name: docker-environment
services:
    data-docker-environment:
        image: data-docker-environment:latest
        build:
            context: data
            dockerfile: Dockerfile
        container_name: docker-db
        networks:
            - my-network
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        restart: unless-stopped
    consumer-docker-environment:
        image: consumer-docker-environment:latest
        build:
            context: src
            dockerfile: Docker.Environment.Consumer.API/Docker/DEV/Dockerfile
        volumes:
            - ./src:/src
            - /src/Docker.Environment.Consumer.API/obj/
            - /src/Docker.Environment.Consumer.API/bin/
            - /src/Docker.Environment.Data.Database/obj/
            - /src/Docker.Environment.Data.Database/bin/
            - /src/Docker.Environment.Data.Models/obj/
            - /src/Docker.Environment.Data.Models/bin/
        container_name: consumer
        depends_on:
            - data-docker-environment
        networks:
            - my-network
        ports:
            - 5000:80
            - 5001:443
        restart: unless-stopped
    commands-docker-environment:
        image: commands-docker-environment:latest
        build:
            context: src
            dockerfile: Docker.Environment.Commands.API/Docker/Dockerfile
        container_name: commands
        depends_on:
            - data-docker-environment
        networks:
            - my-network
        ports:
            - 5002:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped
networks:
    my-network:
volumes:
    pgdata: